
package com.estar.sbe.ws.retrievepnr;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.3
 * 2016-11-10T16:41:25.233Z
 * Generated source version: 3.1.3
 */

@WebFault(name = "FunctionalException", targetNamespace = "http://commons.ws.sbe.estar.com/")
public class FunctionalException extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.estar.sbe.ws.commons.FunctionalException functionalException;

    public FunctionalException() {
        super();
    }
    
    public FunctionalException(String message) {
        super(message);
    }
    
    public FunctionalException(String message, Throwable cause) {
        super(message, cause);
    }

    public FunctionalException(String message, com.estar.sbe.ws.commons.FunctionalException functionalException) {
        super(message);
        this.functionalException = functionalException;
    }

    public FunctionalException(String message, com.estar.sbe.ws.commons.FunctionalException functionalException, Throwable cause) {
        super(message, cause);
        this.functionalException = functionalException;
    }

    public com.estar.sbe.ws.commons.FunctionalException getFaultInfo() {
        return this.functionalException;
    }
}
