package com.estar.sbe.ws.retrievepnr;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2016-11-10T16:41:25.260Z
 * Generated source version: 3.1.3
 * 
 */
@WebServiceClient(name = "RetrievePnr", 
                  wsdlLocation = "file:/C:/Balamurugan/My_Workspace/enovation_api/enovation_api/enovation-domain/src/main/resources/wsdl/RetrievePnr.wsdl",
                  targetNamespace = "http://retrievepnr.ws.sbe.estar.com") 
public class RetrievePnr_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://retrievepnr.ws.sbe.estar.com", "RetrievePnr");
    public final static QName RetrievePnrPort = new QName("http://retrievepnr.ws.sbe.estar.com", "RetrievePnrPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Balamurugan/My_Workspace/enovation_api/enovation_api/enovation-domain/src/main/resources/wsdl/RetrievePnr.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RetrievePnr_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Balamurugan/My_Workspace/enovation_api/enovation_api/enovation-domain/src/main/resources/wsdl/RetrievePnr.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RetrievePnr_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RetrievePnr_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RetrievePnr_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    




    /**
     *
     * @return
     *     returns RetrievePnr
     */
    @WebEndpoint(name = "RetrievePnrPort")
    public RetrievePnr getRetrievePnrPort() {
        return super.getPort(RetrievePnrPort, RetrievePnr.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RetrievePnr
     */
    @WebEndpoint(name = "RetrievePnrPort")
    public RetrievePnr getRetrievePnrPort(WebServiceFeature... features) {
        return super.getPort(RetrievePnrPort, RetrievePnr.class, features);
    }

}
