package com.estar.sbe.ws.retrievepnr;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * Interface of RetrievePnrService
 *
 * This class was generated by Apache CXF 3.1.3
 * 2016-11-10T16:41:25.239Z
 * Generated source version: 3.1.3
 * 
 */
@WebService(targetNamespace = "http://retrievepnr.ws.sbe.estar.com", name = "RetrievePnr")
@XmlSeeAlso({com.estar.sbe.ws.commons.output.ObjectFactory.class, com.estar.sbe.ws.retrievepnr.input.ObjectFactory.class, com.estar.sbe.ws.commons.input.ObjectFactory.class, com.estar.sbe.ws.commons.ObjectFactory.class, com.estar.sbe.ws.retrievepnr.output.ObjectFactory.class, ObjectFactory.class})
public interface RetrievePnr {

    @WebMethod
    @RequestWrapper(localName = "searchPnr", targetNamespace = "http://retrievepnr.ws.sbe.estar.com", className = "com.estar.sbe.ws.retrievepnr.SearchPnr")
    @ResponseWrapper(localName = "searchPnrResponse", targetNamespace = "http://retrievepnr.ws.sbe.estar.com", className = "com.estar.sbe.ws.retrievepnr.SearchPnrResponse")
    @WebResult(name = "SearchPnrOutput", targetNamespace = "")
    public com.estar.sbe.ws.retrievepnr.output.SearchPnrOutput searchPnr(
            @WebParam(name = "SearchPnrInput", targetNamespace = "")
            com.estar.sbe.ws.retrievepnr.input.SearchPnrInput searchPnrInput
    ) throws TechnicalException, FunctionalException;

    @WebMethod
    @RequestWrapper(localName = "loadTravel", targetNamespace = "http://retrievepnr.ws.sbe.estar.com", className = "com.estar.sbe.ws.retrievepnr.LoadTravel")
    @ResponseWrapper(localName = "loadTravelResponse", targetNamespace = "http://retrievepnr.ws.sbe.estar.com", className = "com.estar.sbe.ws.retrievepnr.LoadTravelResponse")
    @WebResult(name = "LoadTravelOutput", targetNamespace = "")
    public com.estar.sbe.ws.retrievepnr.output.LoadTravelOutput loadTravel(
            @WebParam(name = "LoadTravelInput", targetNamespace = "")
            com.estar.sbe.ws.retrievepnr.input.LoadTravelInput loadTravelInput
    ) throws TechnicalException, FunctionalException;
}
