
package com.estar.sbe.ws.retrievepnr;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.3
 * 2016-11-10T16:41:25.205Z
 * Generated source version: 3.1.3
 */

@WebFault(name = "TechnicalException", targetNamespace = "http://commons.ws.sbe.estar.com/")
public class TechnicalException extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.estar.sbe.ws.commons.TechnicalException technicalException;

    public TechnicalException() {
        super();
    }
    
    public TechnicalException(String message) {
        super(message);
    }
    
    public TechnicalException(String message, Throwable cause) {
        super(message, cause);
    }

    public TechnicalException(String message, com.estar.sbe.ws.commons.TechnicalException technicalException) {
        super(message);
        this.technicalException = technicalException;
    }

    public TechnicalException(String message, com.estar.sbe.ws.commons.TechnicalException technicalException, Throwable cause) {
        super(message, cause);
        this.technicalException = technicalException;
    }

    public com.estar.sbe.ws.commons.TechnicalException getFaultInfo() {
        return this.technicalException;
    }
}
